export enum VoucherStatus {
  CREATED = 'CREATED',
  RECEIVED = 'RECEIVED',
  REJECTED = 'REJECTED',
  RETURNED_TO_SENDER = 'RETURNED_TO_SENDER',
  RETURNED_TO_SUPPLIER = 'RETURNED_TO_SUPPLIER',
  CANCELLED = 'CANCELLED',
}
